### ISSUE TITLE
Restructure Package Meta

### ISSUE THREAD

**Issue by RayhanADev** [ReplAPI-it/ReplAPI.it-NodeJS#68]
This issue correlates with [the similar project](https://github.com/ReplAPI-it/ReplAPI.it-NodeJS/projects/2). Tasks include:
- [ ] Redesign the Custom Class to match up with the current design of API Classes
- [ ] Implement [lightfetch](https://github.com/RayhanADev/lightfetch) for HTTPS fetching (#67)
- [ ] Add helper functions to parse custom Objects to GraphQL querystrings
- [ ] Rewrite all API Classes to [dogfood](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) the new Custom Class

This will be released as 2.4.x, a minor version and beta releases will be made under 2.4.0-beta.x. As always, help is appreciated!

**Comment by RayhanADev** [comment]
Code to Parse Objects to GraphQL Querystrings!:
```js
function whatis(value) {
	return Object.prototype.toString.call(value)
		.replace(/^\[object\s+([a-z]+)\]$/i, '$1')
		.toLowerCase();
}

function createQueryVariablesString(queryVariables) {
	let queryString = "";
	for (const [key, value] of Object.entries(queryVariables)) queryString += `$${key}: ${value},`;
	return queryString.slice(0, -1);
}

function createQueryItemsString(queryItems, tabLength = 1) {
	let queryString = "";
	let tabPadding = "";
	for(let i = tabLength; i > 0; i -= 1) tabPadding += '\t';
	for (const [key, value] of Object.entries(queryItems)) {
		switch(whatis(value)) {
			case "string":
				queryString += `${tabPadding}${key}\n`;
				break;
			case "array":
				const propOptions = Object.entries(value[0]).join('* ').replace(/,/g, ': $').replace(/\*/g, ',');
				const propAlias = value[1];
				queryString += `${tabPadding}${propAlias ? `${propAlias}: ` : ''}${key}${propOptions ? `(${propOptions})` : ''}\n`
				break;
			case "object":
				queryString += `${tabPadding}${key} {\n${tabPadding}\titems { \n${createQueryItemsString(value.items, 3)}\n${tabPadding}\t}\n${tabPadding}}\n`;
				break;
			default:
				throw new Error('Unknown type.');
				break;
		}
	}
	return queryString.slice(0, -1);
}

function createQueryWrapper(queryName, queryVariables, queryProperties) {
	const queryTemplate = 'query __QUERY_NAME__(__QUERY_VARIABLES__) {\n__QUERY_PROPERTIES__\n}';
	const queryVariablesString = createQueryVariablesString(queryVariables);
	const queryPropertiesString = createQueryItemsString(queryProperties);

	return queryTemplate
		.replace(/__QUERY_NAME__/, queryName)
		.replace(/__QUERY_VARIABLES__/, queryVariablesString)
		.replace(/__QUERY_PROPERTIES__/, queryPropertiesString);
}

const items = {
	username: "",
	firstName: "",
	lastName: "",
	karma: "",
	url: [{"lite": "lite"}, 'lite'],
	posts: {
		args: [{"count": "count", "after": "after", "order": "order"}],
		items: {
			id: "",
			title: "",
			body: "",
			preview: [{"length": "length", "removeMarkdown": "removeMarkdown"}]
		}
	}
}

const variables = {
	username: "String!"
};

console.log(createQueryWrapper('UserInfo', variables, items));
```

**Comment by RayhanADev** [comment]
Turned this hunk of code into a neat package: https://github.com/RayhanADev/gql-query-creator

**Comment by RayhanADev** [comment]
Rewrote the Board class with the new structure and it works beautifully!!!

**Comment by RayhanADev** [comment]
Publicly released [`replapi-it@2.4.0-beta.2`](https://www.npmjs.com/package/replapi-it) which should give some idea of what it feels out of source. I posted the package size [here](https://github.com/ReplAPI-it/ReplAPI.it-NodeJS/issues/69#issuecomment-866423538) and there is a huge decrease in size (good!). Several classes work with the new structure.
